/*==============================================================================================
Autor         : AngelaAndrade[Kalettre]
Fecha         : 24/04/2023
Item Azure  : 29175 - Envio de giros
Descripcion : Inserción de los datos necesarios para la tabla comunicacion_socket
===============================================================================================*/


INSERT INTO public.comunicacion_socket (id,ip,puerto) VALUES ('1','ip_socket','puerto_socket');

commit;